# Generated by Django 5.1.3 on 2025-11-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock disponible en unidades enteras'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock disponible en unidades enteras'),
        ),
    ]
